# This is the first ansible's project , a kind of Hello World :)
---
- name: This is a hello world project
  hosts: all
  gather_facts: false
  become: yes

  roles:
    - common
    - php
    - nginx
    - mysql
