---
- name: Add repository to install php7
  apt_repository: repo='ppa:ondrej/php' state=present update_cache=yes

- name: Install php7
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - php7.0
    - php7.0-fpm
    - php7.0-mysql
    - php7.0-xml